### PR TITLE
only update DNS when different

### PR DESCRIPTION
**Pull request by nicholascioli**
This PR updates the script to only update the DNS record in cloudflare when it changes. This should reduce the amount of API calls, since DNS entries tend not to change too often.

I have `dig` fetching directly from `1.1.1.1`, since we only care about cloudflare DNS entries, but let me know if you'd prefer to have it just use the container's upstream DNS servers instead.

### CODE REVIEW

**Comment by mirioeggmann** [comment]
Hey @nicholascioli

Thank you very much for your contribution! 
Great enhancement and it is perfectly fine for me with the Cloudflare DNS (1.1.1.1).

Cheers
Mirio

**Comment by yoyozbi** [comment]
FYI: This doesn't work when the record is proxied :smile:

**Comment by mirioeggmann** [comment]
Hey @yoyozbi true, but it also doesn’t break the functionality for you right?

But I will have to include a check if PROXIED is set to true and not execute the dig command if so.

Do you have an idea how we can solve the "problem" if PROXIED is set to true?
Because I see no other way than first querying the Cloudflare API to check if the IP changed and then updating the record, but then we can also just update it directly (so we do not have to make two calls to the API) 😅

**Comment by yoyozbi** [comment]
Hello @mirioeggmann,

Sorry for the late response, No this doesn't break the functionality it only push the new IP every time.
We cannot know the real IP without querying cloudflare. The only way it would possible (I think) is by storing somewhere (via a pv ?) the last address sent and check if it has changed.

**Comment by mirioeggmann** [comment]
Hey @yoyozbi 

True that might be a way :) Maybe to prevent the use of persistent volumes we could also change it from a CronJob to a normal Pod? Then we could store it ephemeral in the Pod which could be easier for some home cluster setups, because not all support PV(C)'s out of the box. And yes we would have to update/query it again if the Pod restarts but I think this should be okey?

**Comment by yoyozbi** [comment]
Great idea ! It will be  better with a deployment, I don't see another way to save requests

**Pull request merged**
